project:
  type: website

website:
  title: "Fiona Jeweler"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Courses
        href: courses.qmd
      - text: Outside the Classroom
        href: outside.qmd
      - text: Resume/CV
        href: resume.qmd
  page-footer:
    background: light
    left: Copyright 2025, Fiona Jeweler
    right: >
      This website is built with 
      <i class="fas fa-heart" title="a heart"></i>, 
      <a href="https://github.com/samanthacsik/samanthacsik.github.io" target="_blank">
        <i class="fab fa-github" title="GitHub octocat logo"></i>
      </a>, 
      <a href="https://www.r-project.org/about.html" target="_blank">
        <i class="fab fa-r-project" title="R Project"></i>
      </a> and 
      <a href="https://quarto.org/" target="_blank">Quarto</a>

format:
  html:
    theme: flatly
    mainfont: Nunito
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

editor: visual
output-dir: docs

